mzml_dir: "data/spectra/mouse_samples/subset_spectra_for_testing"
parent_results_dir: "results/test"
samples: [
  "BMEM_AspN_Fxn4",
]
fasta: "fastas/SwissProt.TAW_mouse_w_NOD_IAPP.fasta"
crux_comet_params: "comet/crux.comet.params"
top_n_proteins: 10
q_value_threshold: 0.5
precursor_mz_ppm_tol: 20
peak_to_ion_ppm_tol: 20