{% set version = "4.2" %}

package:
  name: crux-toolkit
  version: {{ version }}

source:
  - url: https://noble.gs.washington.edu/crux-downloads/crux-{{ version }}/crux-{{ version }}.Linux.x86_64.zip  # [linux]
    sha256: b5c1a02416f0220beb6106e12a7b330932dec396291ae364af8f2153a1e1655d  # [linux]
  - url: https://noble.gs.washington.edu/crux-downloads/crux-{{ version }}/crux-{{ version }}.Darwin.x86_64.zip  # [osx]
    sha256: 5f1fb9124391cec30608740fdce3aea7fcb3f19330531ea90f6ecf81b8583d00  # [osx]

build:
  number: 2
  script: "mkdir -p $PREFIX/bin; chmod a+x bin/*; cp bin/* $PREFIX/bin"

requirements:
  build:
    # both needed as run-time dependencies
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - crux version 2> /dev/null | grep -q 'Crux version'

about:
  home: http://crux.ms
  summary: A cross-platform suite of analysis tools for interpreting protein mass spectrometry data
  license: Apache-2.0
  license_family: Apache
  dev_url: https://github.com/crux-toolkit/crux-toolkit

extra:
  skip-lints:
    - should_not_be_noarch_source
